apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-postgres
  template:
    metadata:
      labels:
        app: posts-postgres
    spec:
      containers:
        - name: posts-postgres
          image: postgres
          env:
            - name: POSTGRES_DB
              value: posts_database # Имя базы данных
            - name: POSTGRES_USER
              value: posts_user # Имя пользователя
            - name: POSTGRES_PASSWORD
              value: posts_password # Пароль пользователя
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data # Путь к каталогу данных PostgreSQL
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: posts-postgres-pvc # Имя Persistent Volume Claim
---
apiVersion: v1
kind: Service
metadata:
  name: posts-postgres-srv
spec:
  selector:
    app: posts-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: posts-postgres-pv
spec:
  capacity:
    storage: 1Gi # Размер хранилища
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/host/directory" # Путь на узле кластера Kubernetes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: posts-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Размер запрашиваемого хранилища
